# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test-nbdev',
                'doc_host': 'https://james.d.hasselman@gmail.com.github.io',
                'git_url': 'https://github.com/james.d.hasselman@gmail.com/test-nbdev',
                'lib_path': 'test_nbdev'},
  'syms': {'test_nbdev.core': {'test_nbdev.core.foo': ('core.html#foo', 'test_nbdev/core.py')}}}
